import localFont from "next/font/local";
import { Poppins } from 'next/font/google';
import "./globals.css";
import { Suspense } from 'react';  // Import Suspense dari React
import ClientLayout from './_components/ClientLayout'; // Import komponen Loading

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const poppins = Poppins({
  subsets:['latin'],
  weight:['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata = {
  title: "Malpres 2024",
  description: "Generated by IT Malpres",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Bungkus children dengan Suspense dan tampilkan Loading saat konten belum dimuat */}
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
